import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "@/components/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="antialiased flex flex-col md:flex-row"
      >
        <Sidebar />
        <main className="flex-1 md:ml-64 p-4 pb-20 md:pb-4">
          {children}
        </main>
      </body>
    </html>
  );
}
